# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sorvete.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsorvete.proto\".\n\x0eSorveteRequest\x12\r\n\x05\x62olas\x18\x01 \x01(\x05\x12\r\n\x05sabor\x18\x02 \x01(\t\"#\n\x0fSorveteResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t2=\n\x07Sorvete\x12\x32\n\rPedidoSorvete\x12\x0f.SorveteRequest\x1a\x10.SorveteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sorvete_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SORVETEREQUEST._serialized_start=17
  _SORVETEREQUEST._serialized_end=63
  _SORVETERESPONSE._serialized_start=65
  _SORVETERESPONSE._serialized_end=100
  _SORVETE._serialized_start=102
  _SORVETE._serialized_end=163
# @@protoc_insertion_point(module_scope)
