# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sorvete_pb2 as sorvete__pb2


class SorveteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PedidoSorvete = channel.unary_unary(
                '/Sorvete/PedidoSorvete',
                request_serializer=sorvete__pb2.SorveteRequest.SerializeToString,
                response_deserializer=sorvete__pb2.SorveteResponse.FromString,
                )


class SorveteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PedidoSorvete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SorveteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PedidoSorvete': grpc.unary_unary_rpc_method_handler(
                    servicer.PedidoSorvete,
                    request_deserializer=sorvete__pb2.SorveteRequest.FromString,
                    response_serializer=sorvete__pb2.SorveteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sorvete', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sorvete(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PedidoSorvete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sorvete/PedidoSorvete',
            sorvete__pb2.SorveteRequest.SerializeToString,
            sorvete__pb2.SorveteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
